# Generated by Django 2.1.4 on 2019-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbraininputs',
            name='use_full_sample',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
